language: python
python:
  - "3.6"
# all scripts will be in docker composer 
services: 
  - docker

# before script
before-script: pip install docker-compose
script:
  # - docker-compose up --build
  - docker-compose run app sh -c "python manage.py test && flake8"